### ISSUE TITLE
content folder is empty.. its no good

### ISSUE THREAD

**Issue by mediaexplorer74** [soopercool101/CutTheRopeAP#2]
Hi. [soopercool101](https://github.com/soopercool101)!
Nice project but... content folder is empty! If you not in U.S. and E.U. colony, please share content data :)

Best / Cheers up,
Om nom nom
Russia

**Comment by soopercool101** [comment]
Content folder was removed intentionally for copyright reasons. A valid steam version is required to build, sorry

**Comment by mediaexplorer74** [comment]
> Content folder was removed intentionally for copyright reasons. A valid steam version is required to build, sorry

Ok. I understood you. Steam still not banned in Russia after starting "Half-world-wide Cancelled Country [W]isteria". Ok, I'll try to sell/buy Cut The Rope A. to continue reverse-engeneering and UWP porting.
Thank you for quick answer(ing) & interesting research project...
